//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRegister.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int RId { get; set; }
        public int LoginId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Role { get; set; }
    
        public virtual TblLogin TblLogin { get; set; }
    }
}
